### ISSUE TITLE
macOS build should have "About Theengs" and "Preferences   ⌘," menu items

### ISSUE THREAD

**Issue by DigiH** [theengs/app#14]
Nothing major, but again going a long way in making the macOS build appear Mac like and adhering to macOS standards, it should have

About Theengs
----------------
Preferences   ⌘,
----------------

on top of the current application menu items

<img width="211" alt="Screenshot 2022-06-28 at 14 48 09" src="https://user-images.githubusercontent.com/17110652/176182551-84f475ca-81ee-4d4e-ac14-bc3f515bd5ab.png">

These menu entries are the minimum of every single macOS application, and even Microsoft themselves adhere to that rule with every of their macOS applications.

<img width="280" alt="Screenshot 2022-06-28 at 15 00 50" src="https://user-images.githubusercontent.com/17110652/176184969-69bec64c-a94d-4f1b-ba25-2d1a8aeeb047.png">

Surprisingly enough, the Preferences keyboard shortcut ⌘, is already working and implemented in

https://github.com/theengs/app/blob/development/qml/DesktopApplication.qml#L299

and from reading 

https://doc.qt.io/qt-6/qkeysequence.html

this **Preferences** StandardKey is a macOS only implementation already.

So adding these two menu items would only additionally require that the **About Theengs** would also go to/open `appContent.state = "About"` and the menu would look totally familiar and as expected to every macOS user.

**Comment by emericg** [comment]
Can you have a look at the latest macOS versions? There is an app menu now.

**Comment by DigiH** [comment]
Verified with 1.1 as addressed. Closing.
