### ISSUE TITLE
Theengs theme selection ring colour orange hardly visible on orange rssi devices

### ISSUE THREAD

**Issue by DigiH** [theengs/app#16]
While in the snow theme and the night theme the selection ring colour of selected devices in the visual view are easily distinguishable for all rssi device colours, in the default Theengs theme any not so good rssi devices are orange themselves and and not as clearly visible when selected

<img width="193" alt="Screenshot 2022-06-28 at 17 20 13" src="https://user-images.githubusercontent.com/17110652/176227290-485513a7-69ea-4678-b232-d78aea77b5a5.png">

as the green rssi devices are.

<img width="123" alt="Screenshot 2022-06-28 at 17 19 31" src="https://user-images.githubusercontent.com/17110652/176221707-538e9772-20e3-4e47-acca-a03eca76033c.png">

Since the default Theengs theme heading colour is blue, I thought it might be nice to have the same blue selection ring colour for easy visibility of all rssi devices.

Similar to
https://github.com/theengs/app/issues/15
while I think this would be nice, since it is not really a vital functionality issue, it can be considered as nice to have possibly later or even not to be fixed.

**Comment by emericg** [comment]
Can you have a look at the latest macOS versions? This should be better.

**Comment by DigiH** [comment]
Verified with 1.1 as nicely discernible with blue selection ring. Closing as fixed.
