### ISSUE TITLE
SAMSUNG j7 can not connect broker

### ISSUE THREAD

**Issue by NIK-TAIWAN** [theengs/app#25]
**Describe the bug**
impossible to get connection to Hive MQ
Top right stay DISCONNECTED
ID/PASSWORD double checked

**To Reproduce**
HiveMQ Cloud
APP on android / samsung galaxyJ7 prime

[Theengs.pdf](https://github.com/theengs/app/files/9695999/Theengs.pdf)

**Expected behavior**
should connect to broker to statrt push MSG

**Screenshots**

**Environment (please complete the following information):**
* version used (V0.9.3, 0.8, development)
* v1.0
* 
* Context of your projec

**Additional context**

* You should not have a compilation error if you use the versions of the libraries linked into the libraries folder, this badges show you the state of the compilation 
[![Build Status](https://github.com/theengs/app/workflows/Build/badge.svg?branch=development)](https://github.com/theengs/app/actions)
* If you are not sure this is a bug or an enhancement post your question to the forum

**Comment by 1technophile** [comment]
Hello,

Only port 1883 (nonencrypted) is supported, as most local MQTT brokers provided are configured with this port.
Port 8883 requires a certificate.
I'm thinking on adding the support of cloud brokers. Could you tell me more about the use case?

Regards

**Comment by NIK-TAIWAN** [comment]
Hello,

On the Theengs APP website HiveMQ is listed as one of the broker compatible with the APP

<img width="1204" alt="Capture d’écran 2022-10-03 à 22 06 47" src="https://user-images.githubusercontent.com/114908597/193598700-019279d9-13c1-4afa-b555-508ce76c5cb7.png">


Florian, je fais des saucissons a Taiwan, comme c'est un pays chaud et humide, le suivi en T et Humid de mon sechoir est un gros soucis. J'ai des inkbird sensor/gateway dans le sechoir pour suivre sur mon cell. Maintenant je veux integrer ces data T/Humid en live sur mon HA sur un NAS,chez moi pour pouvoir via Node-red piloter des smart lpug dans le sechoir. Le sechoir est a 10KM de chez moi, pas de VPN, donc Hive est une solution, et comme Hive est anoncé comme supporté, c'est pour cela que j ai acheté l APP.

**Comment by 1technophile** [comment]
Cool use case, do you plan to let a cell phone permanently close to the dryer?

I would suggest [OpenMQTTGateway ](https://docs.openmqttgateway.com/) on an ESP32 for this use case, as the scanning frequency can be done at a higher rate than through the app.
OpenMQTTGateway support port 8883 and certificates.
If you are not familiar with PlatformIO, I can provide you a binary for it.

For the mobile app, it will only work on a HiveMQ installation that uses port 1883, idealy local one.

**Comment by NIK-TAIWAN** [comment]
My apologises, I assumed that HiveMQ is always cloud, so I thought Theengs provided this cloud based broker connection.

I was reading about OpenMQTTGateway and it is where I found Theengs. I was very excited by OpenMQTT gateway, but as I have an old android phone available , I was planning to do a prototype on it with your APP.

OpenGateway+ESP32 sounds exciting but far from my current knowledge. How bad is the learning curve, as I would like to be able to tune the solution by myself afterwards?

**Comment by 1technophile** [comment]
Once we get a binary compatible with HiveMQ, it is mostly about flashing it to the esp32 and doing the config through a web portal.
Do you have Wifi, where you have your dryer?

**Comment by NIK-TAIWAN** [comment]
Test de connection APP / Sensor OK

![IMG_1483](https://user-images.githubusercontent.com/114908597/193869660-47125ef0-b045-4b2a-9dc7-0daed246bcf4.JPG)

Later, I created a VPN and a broker on HA in order to get a local broker, then your APP connected and sent data perfectly.

All good

Wifi is available in dryer

**Comment by 1technophile** [comment]
Good idea! And glad you got it working.

Please note the [tips](https://app.theengs.io/use/use.html#android) to have updates running in the background.

If you are still interested in ESP32 let me know

**Comment by NIK-TAIWAN** [comment]
Hello Florian,

I have strange data arriving on my MQTT broker from the Theengs APP.
Data that are related to the sync. sensor in the APP (inkbird IBBQ), but also other sensor that are not displayed in the APP

Many hanks for your input

![IMG_1503](https://user-images.githubusercontent.com/114908597/195068661-ae27d9d6-d9e2-493b-858f-b6c9fef1c352.JPG)
![IMG_1502](https://user-images.githubusercontent.com/114908597/195068802-fea271e1-f1c5-4b90-8da8-4c7c40c4a34e.JPG)

**Comment by DigiH** [comment]
Hi @NIK-TAIWAN,

all the **GEAN** messages you see in the MQTT broker log with MQTT-Explorer are [Google/Apple Exposure Notification](https://decoder.theengs.io/devices/GAEN.html) broadcasts sent out by devices in your area with the Covid contact app installed.

They do not show up in the Theengs APP, as they would not make any sense there or give any additional value, but are currently being broadcast to the MQTT broker. 

So you don't have to worry, they are nothing bad, and you can just ignore them in the broker messages.

**Comment by NIK-TAIWAN** [comment]
Ok, understand...sure it is easy to filter

But what is the point to broadcast irrelevant/unwanted traffic? 


    On Tuesday, October 11, 2022 at 07:59:15 PM GMT+8, DigiH ***@***.***> wrote:  
 
 


Hi @NIK-TAIWAN,

all the GEAN messages you see in the MQTT broker log with MQTT-Explorer are [Google/Apple Exposure Notification](Google/Apple Exposure Notification) broadcasts sent out by devices in your area with the Covid contact app installed.

They do not show up in the Theengs APP, as they would not make any sense there or give any additional value, but are currently being broadcast to the MQTT broker.

So you don't have to worry, they are nothing bad, and you can just ignore them in the broker messages.

**Comment by 1technophile** [comment]
Hello,

We will filter IBEACON,GAEN and MS-CDP advertisements in the next version of the app

**Comment by NIK-TAIWAN** [comment]
Hello Florian,

I am the saucisson maker in Taiwan.

Just found out about the Theengs PLUG

Thanks a lot for this amazing product

I think I will buy one or two for my 'sechoir'

**Comment by NIK-TAIWAN** [comment]
Any ways to get it outside the US?

**Comment by 1technophile** [comment]
I did not know that Taiwan uses the same plug as the US, let me see the options

**Comment by 1technophile** [comment]
@NIK-TAIWAN you can contact me to this email florian@theengs.io

**Comment by NIK-TAIWAN** [comment]
Plug is different but voltage & frequency are same


Le mercredi, mars 1, 2023, 11:41 PM, Florian ***@***.***> a écrit :




I did not know that Taiwan uses the same plug as the US, let me see the options

**Comment by 1technophile** [comment]
Got it, you can send me an email if you are interested

**Comment by 1technophile** [comment]
Fixed
