### ISSUE TITLE
Swipe behaviour to be iOS consistent

### ISSUE THREAD

**Issue by DigiH** [theengs/app#27]
While on the main list view page a (from very left edge of the screen to the right) swipe brings up the options side bar, otherwise called up by the burger menu, but when being in a detail widget view this swipe should adhere to the iOS standard of going **back** - as not to have to reach all the way up to the top left to hit the back arrow.

If the swipe behaviour cannot be assigned differently to different view I'd prefer it to always have the default back behaviour as this would be user a lot more often than calling up the options side bar.

The default behaviour can most easily be seen in the iOS Preferences, and most other iOS apps.

**Comment by 1technophile** [comment]
As this is more complex to have the swipe doing a back, we will remove the swiping behavior for the two pages (main and sensor content)

**Comment by DigiH** [comment]
Verified with version 1.1 (1010008) to not have a swipe behaviour any longer. Closing

**Comment by DigiH** [comment]
Back with 1.1.1 (1010101) that swipe from very left to right always brings up the Theengs sidebar.

**Comment by 1technophile** [comment]
I confirm with 1.1.1 (1010101) that the Swipe behavior came back

**Comment by emericg** [comment]
Indeed, small problem on my end trying to have a disabled swipe to open the drawer, but keeping the possibility to close an opened drawer with a swipe. Should be ok now.

**Comment by DigiH** [comment]
Closing as fixed in 1.2 (1020001), swipe left-right doesn't do anything, swipe right-left nicely closes the drawer if it's open.
