### ISSUE TITLE
Inconsistent temperature displays for Inkbird iBBQ thermometers

### ISSUE THREAD

**Issue by DigiH** [theengs/app#29]
Tested with version 1.1 (1010008)

For my IBT-2X there are three different inconsistent temperature displays. Assuming the same for the remaining IBT iBBQ thermometers with 4 and 6 probes/Tenergy SOLIS 6 BBQ

Rounded temperature in list view with no decimals and only the degree unit sign

![listview](https://user-images.githubusercontent.com/17110652/198711023-4870cb2b-1133-44fc-9e5d-aab1bbc26886.jpg)

Temperatures in the widget view, with one decimal place, degree unit sign and Celsius sign, then when sliding over the history graph, only the temperatures with one decimal but no degree unit nor Celsius

![IMG_1694](https://user-images.githubusercontent.com/17110652/198710952-8156e2f8-d4fe-44b5-9322-12b54b34f4cd.jpg)

So **21º**, **20.9ºC** and **20.9** all for the same temperature.

My suggestion here would be to follow the Inkbird iBBQ thermometers themselves by not displaying any decimals at all, especially with the high temperatures of BBQ thermometers I don't think it is necessary here and still allows for the shorter display to fit in the list view, especially with 6 temperatures.

Also to only use the degree unit sign **º** everywhere, but NOT the C for Celsius, as this is defined in the preferences anyway. I would not display **C** or **F** anywhere for temperatures in the app. The user knows which unit system they selected ;)

My vote for rounded no decimal only degree unit **21º** everywhere for all iBBQ thermometers.

For any other temperatures I would suggest a one decimal only degree unit **22.7º** format.

**Comment by emericg** [comment]
I'm OK with no decimal and ° in the probe screen.
The ° only in every screen why not, it's as you prefer.

**Comment by 1technophile** [comment]
Let's do no decimal for the BBQ sensors. I prefer to keep the C and the F for the unit display.

**Comment by 1technophile** [comment]
ok for me on iOS with build 1010101

**Comment by DigiH** [comment]
Closing as fixed in 1.1.1 (1010101) - all IBT-2X temperatures as rounded integers.
