### ISSUE TITLE
Small graphics clipping in Qingping Air Monitor Lite widget and CO₂ subscript proposal

### ISSUE THREAD

**Issue by DigiH** [theengs/app#30]
Tested with version 1.1 (1010008)

Really nice list view indicating the CO2 state, and details widget with all the remaining properties!

On a smaller iOS screen the widget graphic has a slight clipping at the top.
![airmonitor](https://user-images.githubusercontent.com/17110652/198718768-35409596-cc0e-49e0-888d-6cf138c5f101.jpg)

Also wondering if CO2 could be written with subscript 2 - **CO₂** everywhere - similar to the already implemented superscript **³** in the PM unit **μg/m³**

**Comment by emericg** [comment]
I'm fixing the clipping.
Regarding the CO₂, it's whatever you like best. I don't particularly think it looks better in most places.

**Comment by 1technophile** [comment]
Okay to have it like this, CO₂

**Comment by DigiH** [comment]
Closing as fixed in 1.1.1 (1010101).
