### ISSUE TITLE
Relative Humidity unit on Qingping Air Monitor Lite page 

### ISSUE THREAD

**Issue by DigiH** [theengs/app#32]
Tested with version 1.1 (1010008)

The current display shows **ºRH** for the unit of the humidity. 

Should be using the percentage **%** sign instead of the degree **º**

I'm also don't think we need to specify the RH - Relative Humidty - only for this particular case, as all the other thermometer humidity displays only show % and they all are also showing the relative humidity. So just % will be fine here as well.

![RelativeHumidity](https://user-images.githubusercontent.com/17110652/198834477-eb300fe0-0fbb-4e90-8daf-34eb970e4f4b.jpg)

vs.

![humidity](https://user-images.githubusercontent.com/17110652/198834690-10b069d8-2733-4f64-8fc9-d046a1f69d52.jpg)

**Comment by 1technophile** [comment]
Agreed `°RH` can be replaced by `%`

**Comment by 1technophile** [comment]
ok for me on build iOS 1010101

**Comment by DigiH** [comment]
Closing as fixed in 1.1.1 (1010101).
