### ISSUE TITLE
Request to make Home Assistant discovery optional with a switch in the MQTT Integration settings

### ISSUE THREAD

**Issue by DigiH** [theengs/app#54]
With the recent testing of the app's MQQT integration with version 1.2, and for logging https://github.com/theengs/app/issues/52 I found that the newly introduced Home Assistant discovery is not optional, but seems to be always active.

With my all manually textually defined OpenHAB  setup I would rather not have all the auto discovered devices piling up in my in-box, but would like to be able to use the MQTT integration without discovery.

**Comment by emericg** [comment]
Yes I think that made sense to add a switch for the MQTT discovery.

**Comment by emericg** [comment]
That feature has been implemented.

**Comment by DigiH** [comment]
Closing as verified with latest macOS build.
