### ISSUE TITLE
Android app does not send data over mqtt integration

### ISSUE THREAD

**Issue by Davasny** [theengs/app#57]
**Describe the bug**
I bought the android application to send data from my `LYWSD03MMC` to mqtt server but it's not happening. App has found my sensor, connected with it, connected with mqtt server and even sent data to it (`home/TheengsApp/version`) but it doesn't send any data from the sensor.

**To Reproduce**
1. Run app on android device
2. Connect with `LYWSD03MMC` and mqtt server
3. There is no data on mqtt server

**Expected behavior**
Data should appear on mqtt server

**Screenshots**
![image](https://user-images.githubusercontent.com/25726866/206926481-df8b9d42-a859-4e13-94ee-d88c9e367b8c.png)
![image](https://user-images.githubusercontent.com/25726866/206926510-d1b4cecb-fdb9-4ac2-ab06-b6fe89886c30.png)
![image](https://user-images.githubusercontent.com/25726866/206926529-739bdc54-f201-45c0-a422-9c3a88a143d1.png)
![image](https://user-images.githubusercontent.com/25726866/206926536-b05786ca-986a-48d3-abdc-8a1907eef896.png)

**Environment (please complete the following information):**
```
version: 1.2
phone: Redmi Note 7, Android 10, MIUI 12.5.3
mqtt: mosquitto in docker container
mqtt client: mqtt explorer subscribed to #, $SYS/#, home/#, no authorization
```

**Additional context**

* You should not have a compilation error if you use the versions of the libraries linked into the libraries folder, this badges show you the state of the compilation 
[![Build Status](https://github.com/theengs/app/workflows/Build/badge.svg?branch=development)](https://github.com/theengs/app/actions)
* If you are not sure this is a bug or an enhancement post your question to the forum

**Comment by 1technophile** [comment]
Hello,

Thanks for your support.

Did you setup the different android permission like this:
https://app.theengs.io/use/use.html#android

Also, could you try with a username and password

**Comment by Davasny** [comment]
Yes, I did everything about permissions and batery saving.

I've also tried with setting username and password to:
- username: `theengs`, password: `theengs`
- username: `test`, password: `test`

But always I can see only app version in topics

Here are logs from my mosquitto container

```
docker logs -n 1000 mqtt | grep c5d58debb1e44d64bb25046
1670830753: New client connected from 89.70.167.125:46850 as c5d58debb1e44d64bb25046 (p2, c1, k60, u'theengs').
1670830753: Sending CONNACK to c5d58debb1e44d64bb25046 (0, 0)
1670830753: Received PUBLISH from c5d58debb1e44d64bb25046 (d0, q0, r0, m0, 'home/TheengsApp/version', ... (4 bytes))
1670830812: Received PINGREQ from c5d58debb1e44d64bb25046
1670830812: Sending PINGRESP to c5d58debb1e44d64bb25046
1670830872: Received PINGREQ from c5d58debb1e44d64bb25046
1670830872: Sending PINGRESP to c5d58debb1e44d64bb25046
1670830932: Received PINGREQ from c5d58debb1e44d64bb25046
1670830932: Sending PINGRESP to c5d58debb1e44d64bb25046
```

```
cat mosquitto.conf
listener 1883
log_type all
allow_anonymous true
password_file /mosquitto/config/password.txt
```

```
cat mosquitto_pass.conf
theengs:$7$101$Mp5ajTOLXTx3Z89n$5wAgVNTTmkdZGEJo6adLH7TZISlzabBcChRnzRVvQfhHd50FCbQzbR8BIghiTgWBZZoffhg5ZqvaH6x6KbcT+w==
```

**Comment by Davasny** [comment]
I've noticed now there could be some problem with data sync, thermometer had status "synced 35min ago" and I had to tap "update data" to get latest data but it didn't cause sending data to mqtt.

Screen is always on and phone is charging, I have enabled background updates, allowed permisions for location and set interval to 5min

**Comment by emericg** [comment]
Hi Davasny,
The LYWSD03MMC sensor is only supported if it has a custom firmware installed. Otherwise, it's not sending updates over Bluetooth.

https://app.theengs.io/prerequisites/devices.html

**Comment by Davasny** [comment]
Sorry, I missed that fact :/ 

But if doesn't send data over BT how is it possible that application shows measurement?

**Comment by emericg** [comment]
The app connects to the thermometer and manually pulls data, as opposed to "simply" receiving continuously broadcasted data over BLE.
At the moment, no MQTT messages are generated when connecting to a sensor.

**Comment by Davasny** [comment]
I see, thank you for that informations.
I think information about not sending messages on manual refresh should be written somewhere in app (in mqtt integration)

**Comment by Davasny** [comment]
For the future: I can confirm that reflashing sensor to this FW works and I can see data on my mqtt broker

https://github.com/pvvx/ATC_MiThermometer

Thank you very much for your help @emericg and @1technophile
