### ISSUE TITLE
Govee H5101 visible in device browser but not detected.

### ISSUE THREAD

**Issue by jazztunes** [theengs/app#63]
**Describe the bug**
I purchased the Theengs app a few days ago. I have a Govee H5101 thermometer. I can see it in the device browser, but "Launch Detection" doesn't do any thing.  The particular model number is not listed as supported, but it seems it should work because shows up the browser and also it is listed in the theengs/decoder/blob/development/src/devices/H5102_json.h file.

Is this a bug, a device support request, or am I missing something else?

Thanks!

**To Reproduce**
1. BlueTooth enabled.
2. View device browser to verify device is available and not blacklisted
3. Click "Launch Detection"
4. Nothing happens

**Expected behavior**
I believe this device should work since it's visible and seems to be covered by the H5102_json.h file.

**Screenshots**
N/A

**Environment (please complete the following information):**
* Apple iPhone 12

**Additional context**
N/A

**Comment by DigiH** [comment]
Hi @jazztunes,

the H5101 has only been included with Decoder version 1.0.0, which the currently released Theengs App 1.2 doesn't have included yet. With the next update release of the App the Govee H5101 will be included and should then be recognised and decoded as expected - and listed as supported then :)

**Comment by jazztunes** [comment]
Great- I’ll look forward for the new release. Thanks for the quick reply!

**Comment by jazztunes** [comment]
I have the new version of the app (v1.3 on iOS) and my Govee H5101 is recognized and I was able to add it to sensors. However, it shows offline. Can it be that I don't have the MAC address set? I don't know how to find that for my sensor. Anything else I can try?

FYI, it does work correctly in the native "Geovee Home" app.

![Screenshot 2023-03-30 at 11 47 23 AM](https://user-images.githubusercontent.com/10814506/228923511-e604b1ce-f481-4b3c-bf0f-de46737b6ec9.png)

**Comment by DigiH** [comment]
Hi @jazztunes,

Sorry to hear that your Govee H5101  is not showing correctly in Theengs App 1.3.

Which desktop PC do you have? Would you possibly be able to install [Huble-Explorer](https://github.com/koenvervloesem/humble-explorer) or [Theengs Gateway](https://github.com/theengs/gateway)?

This would also allow you to see the H5101's MAC address and the raw data showing there should give us an indication what the issue might be.

**Comment by 1technophile** [comment]
Hello @jazztunes 
I see on your screenshot that you are in discovery mode, when you click on the sandwich menu, and select "refresh sensor data" do you see the data coming?

**Comment by 1technophile** [comment]
@jazztunes just found the issue, fixing it

**Comment by jazztunes** [comment]
Thanks! @1technophile and @DigiH! I see that likely it's fixed - great! I'm guessing it will be in the next version. Something in the decoder? 

FYI, may be unnecessary at this point, but here's more info:

- Refresh sensor data didn't change anything.
- I have HumBLE Explorer running on a Raspberry PI. I see this:

![image](https://user-images.githubusercontent.com/10814506/229211547-18bfbaad-912c-4175-9672-6f664b01cb24.png)

**Comment by DigiH** [comment]
> * I have HumBLE Explorer running on a Raspberry PI. I see this:

This singular manufacturerdata is what the decoder is based upon, but with iOS (and other OSs' versions) there is a broadcast with additional iBeacon data concatenated after the manufacturerdata - something the current decoder doesn't recognise.

Depending which desktop OS you are using, running Humble-Explorer on it might also show you this platform (version) dependant behaviour - so far only observed with most Govee devices.

**Comment by jazztunes** [comment]
Interesting. I also just noticed that I see this in there too. Same name, different manufacturer data:

![image](https://user-images.githubusercontent.com/10814506/229229197-bd462122-6ff4-4443-aa2a-af26215d2092.png)

**Comment by DigiH** [comment]
When it is in separate messages like you see - probably on your RPi - it doesn't affect the proper decoding of the remaining single non-Apple iBeacon messages. The problem which prevented the correct H5101 decoding for you in Theengs App on iOS was when the two were strung together in one message all the time ;)

We're still testing the decoder, but once submitted and integrated into the App it should remedy the non-decoding issues you have been seeing.

**Comment by 1technophile** [comment]
@jazztunes new version with the fix available in the stores, let us know if it fix your issue

**Comment by jazztunes** [comment]
Got the new version and all is well. Sensors show up, readings are coming in through the app and flowing into my MQTT all as expected. Thanks for the quick attention to the issues!

**Comment by 1technophile** [comment]
Thanks for the feedback! 
If you would like feel free to give a review in the store 🙂
