### ISSUE TITLE
Black-listed and deleted devices are back in the list with next search for new sensors

### ISSUE THREAD

**Issue by DigiH** [theengs/app#64]
Blacklisted and deleted devices are back in the list with next search for new sensors, even when the device is still listed as black-listed **⊖** in the device browser.

Verified on iOS and macOS

Also the heading and text for **white-listing** a device in the device browser again is confusingly talking about **black-listing** - i.e. same strings as for initial black-listing - only the button has now changed to **Whitelist**.

<img width="1314" alt="Screenshot 2023-02-06 at 21 15 57" src="https://user-images.githubusercontent.com/17110652/217076239-8f6c506a-da2d-48b7-9367-1894478a5b05.png">

**Comment by emericg** [comment]
Indeed it wasn't working for the devices without MAC, it is now fixed.
I improved the popup too.

**Comment by DigiH** [comment]
Verified with latest macOS build, the functionality is fixed, thanks, but for the whitelisting again the description text still talks about the blacklisting functionality …

<img width="1314" alt="Screenshot 2023-02-07 at 19 57 46" src="https://user-images.githubusercontent.com/17110652/217340324-434ff071-ff03-4e79-8501-c656c4339ded.png">

**Comment by emericg** [comment]
Yeah sure, I didn't see a particular need to change the description, but we can put whatever wording you want here.

**Comment by DigiH** [comment]
Whatever you want and think is appropriate when a user is in the middle of whitelisting a device again, possibly without mentioning "You can un-blacklist the sensor at any time" and "… nothing will happen unless you delete it from the sensor list.".
