### ISSUE TITLE
Device name resets after a short period - Android app

### ISSUE THREAD

**Issue by IMG20191023** [theengs/app#78]
The device name of my BT temperature sensor that I have set resets to the Mac address after a short period/a day.

**Comment by 1technophile** [comment]
Hello,

Thanks for reporting. We are about to release soon a new version that should fix this issue. I will update here.

**Comment by 1technophile** [comment]
The 1.3.1 is available in the stores, let me know if it solve your issue

**Comment by IMG20191023** [comment]
Thank you, I'll test.
