### ISSUE TITLE
Mqtt disconnects

### ISSUE THREAD

**Issue by Almighty1985** [theengs/app#80]
Hey everyone, 

I installed the App today in a Tablet mounted in a Wall near a Bluetooth Sensor and wanted to use IT to Push the Data to my mqtt Server in Home assistant. 

I followed the steps for granting all rights in Android 13 plus making Sure the optinization of accu ist turned Off for the App. 

My Sensor is schön in the App and I also See the Data in my Mqtt Server. But after Like 5 minutes and when the Display goes in sleep Mode, the App loses mqtt Connection and i geht No new Updates for my Sensors. 

Ist there anything i could so to prevent that from Happening?

**Comment by 1technophile** [comment]
Hello,

Thanks for your purchase!
Let me see how we can help you. Could you provide the following information:
* Version of Theengs App installed (see About page)

Can you confirm that these modifications have been done?
* Background updates enable
* The location permission is allowed All the time
* The app is unrestricted in terms of battery life

**Comment by Almighty1985** [comment]
Thanks for leaving a comment. I am currently using version 1.3.2 of the app (installed it out of Google Play today) and I think I have done everything correctly. See attached screenshots (they are german though).

![PXL_20230502_121704188](https://user-images.githubusercontent.com/132346441/235664890-cfa1a221-aae7-47c5-9225-9c1f410957f1.jpg)
![PXL_20230502_121708698](https://user-images.githubusercontent.com/132346441/235664894-7775ac6a-1e76-46df-b055-87679869c08f.jpg)
![PXL_20230502_121727206](https://user-images.githubusercontent.com/132346441/235664896-a69b324a-0d1c-450d-af8f-e4c4e2283770.jpg)
![PXL_20230502_121801860](https://user-images.githubusercontent.com/132346441/235664899-3c807d37-f187-4f61-97fa-e1776c5746c6.jpg)
![PXL_20230502_121808813](https://user-images.githubusercontent.com/132346441/235664900-49db9b60-3408-42af-b6b3-5db359d3642a.jpg)
![PXL_20230502_121819315](https://user-images.githubusercontent.com/132346441/235664902-5739a2c3-4e7c-4515-a0d5-7bb6b8a35ea2.jpg)

**Comment by 1technophile** [comment]
Thanks for the details, give me some time to reproduce the issue and I will get back to you

**Comment by Almighty1985** [comment]
If you need further details Like logs or Android Version just ask :)

**Comment by 1technophile** [comment]
I reproduce the issue with Android 13, let me see if we can fix it ( Android is making it difficult to run BLE scan in the background)

**Comment by 1technophile** [comment]
Do you have this setting to OFF
![image](https://user-images.githubusercontent.com/12672732/235818414-2f71aa99-8a17-4051-89c1-d1cb7ea0b629.png)

**Comment by Almighty1985** [comment]
As I don't have this switch I dug deeper into the system and it seems to be that my device is only Android 10 with no possibility to upgrade to a higher Android version. That seems to be maybe the issue

**Comment by 1technophile** [comment]
Let me try to reproduce with Android 10

**Comment by 1technophile** [comment]
Here are the settings that I propose to try with Android 10:
From the Information page of the app, tap Battery-> Battery optimization->All apps, tap Theengs and select don't optimize
![Screen Shot 2023-05-03 at 2 06 49 PM](https://user-images.githubusercontent.com/12672732/236019127-ab287115-55ca-44b9-a4a4-e1a609c80b5f.png)

From the Information page of the app, tap Mobile data and wifi, switch ON the 2 buttons
![Screen Shot 2023-05-03 at 2 04 51 PM](https://user-images.githubusercontent.com/12672732/236020416-40658b31-7ec6-493e-bdae-3c2065d86c3e.png)

And of course Location should be enabled all the time to allow BLE scanning
![Screen Shot 2023-05-03 at 2 11 03 PM](https://user-images.githubusercontent.com/12672732/236019918-5b523d54-f1eb-45cc-ae22-b64948ffbcd8.png)

![Screen Shot 2023-05-03 at 2 04 11 PM](https://user-images.githubusercontent.com/12672732/236019522-d3311a07-382f-43e8-b567-ab57e80d5560.png)

**Comment by Almighty1985** [comment]
I ahve everything checked as shown in the screenshots. It is working (only two sensors at the moment) as long as the tablet display is on, as soon as the display goes to sleep, the mqtt connection is disabled in the app.

**Comment by 1technophile** [comment]
> It is working (only two sensors at the moment) as long as the tablet display is on, as soon as the display goes to sleep, the mqtt connection is disabled in the app

It should reconnect automatically every X minutes, X being defined in the configuration. You may not see it as connected when you come back to the mqtt configuration in the app.
Do you have a way to check the history of values, either in HA or with an MQTT client like MQTT Explorer?

**Comment by 1technophile** [comment]
Also could you activate your location if not done already:
![image](https://user-images.githubusercontent.com/12672732/236213925-707fc2ec-49d8-44a4-ab1f-43fdf8c8f607.png)

**Comment by Almighty1985** [comment]
I installed MQTT Explorer and I can See the Data now. I had to manually create the Sensors But now IT seems to Work. I get new Data ever 30 minutes. Thanks you very much for your Help.

**Comment by 1technophile** [comment]
Great to hear!

If you don't mind sharing what are the appropriate settings? (I would like to add them to the documentation)

**Comment by Almighty1985** [comment]
I can. What do you need to know exactly?

**Comment by 1technophile** [comment]
Which parameters did you finally use among the ones that we discussed
