### ISSUE TITLE
No MQTT data with iOS App

### ISSUE THREAD

**Issue by london89** [theengs/app#91]
When I added LYWSD03MMC to iOS app, I can see temperature and humidity, can update it.
But in MQTT no data about this.
In MQTT i see only topic home/TheengsApp/version with data "v1.3.1"

1. Install app
2. add LYWSD03MMC 
3. configure mqtt server settings
4. scan MAC of LYWSD03MMC with debian
5. Set MAC Address of my LYWSD03MMC into App, from previous scan
"root@mdm:/home/london# stdbuf -oL hcitool lescan | grep LYWSD03MMC
A4:C1:38:5C:75:B6 LYWSD03MMC"
6. click Update data in app

**Expected behavior**
I wanna LYWSD03MMC data in MQTT

![photo_2023-07-04_20-38-02 (2)](https://github.com/theengs/decoder/assets/28978333/1052c195-8f2b-4e22-9950-fc2a13dab1cf)
![photo_2023-07-04_20-38-02](https://github.com/theengs/decoder/assets/28978333/8e0c250c-67f7-4afd-bf2c-5513c44fd2b7)
![photo_2023-07-04_20-38-00](https://github.com/theengs/decoder/assets/28978333/b7e0db6b-8fdb-44d8-9313-52c739127806)
![photo_2023-07-04_20-37-59](https://github.com/theengs/decoder/assets/28978333/1d13c1fe-62ce-4547-87d1-fd1dfe1aa657)

iOS App Theengs ver 1.3.1
iPhone 14 Pro
iOS ver. 16.5.1

**Comment by DigiH** [comment]
https://github.com/theengs/decoder/issues/388

😃

**Comment by DigiH** [comment]
Just repeating it here as well, in case someone else is experiencing this.

Can you make sure you add your LYWSD03MMC's MAC address at the top right three dots menu - Set MAC address.

As iOS does not allow to recognise devices' MAC addresses, but masks them with random uuids, this is required to be able to assign a constant MAC address to each device. Only then can it publish with this MAC address/id to an MQTT broker.

**Comment by london89** [comment]
> Can you make sure you add your LYWSD03MMC's MAC address at the top right three dots menu - Set MAC addres

of course, you can see it on my screenshot

**Comment by DigiH** [comment]
What about changing the Broker integration name to something other than Mosquitto. I assume you have the Musquitto broker running, but the name which should go in there is the name of the client connecting to Mosquitto, so should likely be something else.


Or just leave them empty for user name and password, as your 1883 port does not indicate any user/password secure connection

Do you have any other connections to the Mosquitto MQTT broker, or is this your first and only connection to it?

**Comment by london89** [comment]
No SSL secure on my MQTT server, so that, port is 1883. But, I use login and password authorisation, and "mosquitto" here is my login for mqtt server.
I see in mosquitto logs successful connections from my phone, and I see topic from The ends App with version of app, 1.3.1. (on my screenshots from MQTT Explorer.
>1688493468: New client connected from 192.168.1.5:49298 as aa39f781e13948a3961beb4 (p2, c1, k60, u'mosquitto').

But no topics with data from my devices.

**Comment by DigiH** [comment]
So the user/password file contains a general user/password combination, which you already use with other clients? Or have you added a new user/password combination for Theengs App? For the latter have you reloaded the file/restarted Mosquitto?

**Comment by london89** [comment]
Yes, with this login/password  I use all my clients. And I see "version topic" from Theengs App, means, Theengs have connect to my server and have permission to write new topics.

**Comment by DigiH** [comment]
Correct, then I'll need to leave the issue for @1technophile or @emericg, as to why the non-SSL, but user/password authenticated connection to the MQTT broker might not work here.

Myself running 1.3.1 on iOS 16.5.1 as well, but without user/password authentication, everything is published fine.

**Comment by london89** [comment]
I don't think, that problem in mqtt authorization, because, in mqtt logs i see, that connection from phone is success and i see topic with application version from Theengs app on my iPhone...

**Comment by DigiH** [comment]
I wouldn't have thought so either, but the only thing I can think about currently is deleting the MAC address entry again and re-entering it afresh, as this is usually a culprit, when MQTT publishing doesn't work correctly.

Other than that the only real difference between your and my set up is the user/password authentication, other than that we are both running the same App version, iOS version and the Mosquitto broker.

**Comment by london89** [comment]
I already try re-enter MAC address with different formats. A4:C1:38:5C:75:B6, A4-C1-38-5C-75-B6, A4C1385C75B6, etc...
And already deleting sensors, already reinstall Theengs App.
But nothing works :(
I think. may be, my method of getting MAC isn't correct? 
I have only iPhone and debian with BLE adapter, and I get MAC's with "stdbuf -oL hcitool lescan | grep LYWSD03MMC" linux command.
What's your way to get LYWSD03MMC's MAC?

**Comment by DigiH** [comment]
To be honest, I would assume any arbitrary MAC address would actually do, as Theengs App on iOS would not even know which wold be the correct MAC address for any device, so even AA:BB:CC:DD:EE:FF should do. So your entered MAC address does not look wrong in any way, and how you got it.

Obviously, if there are other Theengs projects or OpenMQTTGateway involved, a correct MAC address is always the preferred option.

You could use [Theengs Gateway](https://github.com/theengs/gateway) on Debian to check for the actual MAC address, and at the same time also see if publishing to your MQTT broker works fine there.

Theengs Gateway documentation

https://gateway.theengs.io/use/use.html

**Comment by london89** [comment]
I tried this, everything is ok. I receive topic's from Theengs Gateway on same MQTT server.
> root@mdm:/home/london# python3 -m TheengsGateway -H "XXXX" -u "mosquitto" -p "XXXX"

![image](https://github.com/theengs/app/assets/28978333/c939abde-0671-4c0c-9e39-f54c9f5cbe94)

And MAC of LYWSD03MMC is the same

**Comment by DigiH** [comment]
Actually, one thing I am seeing though is that the message for your LYWSD03MMC is **NOT** being decoded in the Gateway published message.

With non-decoded messages Theengs App will not publish any  messages, so I think this is the issue here.

Which firmware are you running on your LYWSD03MMC that is is not being decoded by Theengs Decoder?

**Comment by DigiH** [comment]
Theengs Decoder, which does the BLE decoding for Theengs Gateway and Theengs App can only decode LYWSD03MMC if the unencrypted ATC or PVVX firmware protocol is  being used on these devices

https://decoder.theengs.io/devices/LYWSD03MMC.html

The easiest way to flash the PVVX formware onto your LYWSD03MMC would be

https://pvvx.github.io/ATC_MiThermometer/TelinkMiFlasher.html

**Comment by london89** [comment]
Unforchunatly, I have same result...

![photo_2023-07-04_22-07-01](https://github.com/theengs/app/assets/28978333/4c263033-eefb-49d5-bc46-3a70afdd5d99)
![photo_2023-07-04_22-07-00](https://github.com/theengs/app/assets/28978333/3c03ba91-5545-4d21-bc21-a3623002b6a5)

**Comment by DigiH** [comment]
Sorry, same result for which different settings?

**Comment by london89** [comment]
same result for no login/password on mqtt server.
If messages from LYWSD03MMC can't decoded, i think, no temp and hum will be in Theengs App on iOS? But, I have this data in iOS app. Only no mqtt data from this

**Comment by DigiH** [comment]
I did delete again a previous message talking about alternative firmware for LYWSD03MMC devices, which is usually required for correct decoding with Theengs Decoder, generally being used in Theengs Gateway, OpenMQTTGateway and also Theengs App, with Theengs App also having some legacy decoders implemented which might also decode the stock firmware, but might have an issue with publishing such decodings?!?

Theengs Decoder can currently only decode LYWSD03MMC if the **unencrypted** ATC or [PVVX firmware](https://github.com/pvvx/pvvx.github.io) protocol is  being used on these devices

https://decoder.theengs.io/devices/LYWSD03MMC.html

The easiest way to flash the [PVVX firmware](https://github.com/pvvx/pvvx.github.io) onto your LYWSD03MMC would be

https://pvvx.github.io/ATC_MiThermometer/TelinkMiFlasher.html

This should then also give you correct decoded messages in Theengs Gateway, which previously above only showed the undecoded raw data as well.

<img width="764" alt="Screenshot 2023-07-04 at 21 20 22" src="https://github.com/theengs/app/assets/17110652/5fbbbe6f-6903-4245-b7af-18466fed1d08">

**Comment by london89** [comment]
I can't flash this from iOS or non-GUI debian?

**Comment by DigiH** [comment]
Apologies for all the hoo-haa with this!

You and me both only just got to realise what intricacies Theengs App holds for this special case :( 

Me not having a LYWSD03MMC myself here, I don't actually know how you could get the PVVX firmware installed with only iOS and non-GUI Debian. 

We will definitely look into this matter more closely and hope to find a solution soon. Please bear with us for a bit.

**Comment by london89** [comment]
After flashing LYWSD03MMC from Android phone to ATC firmware - everything is ok. Thank you for your help!

<img width="432" alt="image" src="https://github.com/theengs/app/assets/28978333/2d698508-1535-4c8c-b348-cd7114b916de">
